export interface ChildRegistrationData {
    _id: string,
    childFirstName: string,
    childLastName: string,
    childSport: string,
    dateOfBirth: string,
    gender: string,
    guardianFirstName: string,
    guardianLastName: string,
    guardianEmail: string,
    guardianStreetAddress: string,
    guardianCityS: string,
    guardianZipCode: string,
    guardianState: string,
    annualHouseHoldIncome: number,
    showcaseVideoLink: string,
    childStory: string,
    isPlaced: boolean,
    createdAt: string,
    updatedAt: string,
    age: number
}